package com.datacap.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ConfigBase generated by hbm2java
 */
@Entity
@Table(name = "CONFIG_BASE", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = {"CID"}) )
public class ConfigBase implements java.io.Serializable {

	private int cid;
	private int qrZoneX;
	private int qrZoneY;
	private int qrZoneWidth;
	private int qrZoneHeight;
	private String uploadLocation;
	private String cmisProtocol;
	private String cmisUri;
	private String cmisUsername;
	private String cmisPassword;
	private String cmisAuthHttpBasic;
	private String cmisRepository;
	private String cmisExportFolder;

	public ConfigBase() {
	}

	public ConfigBase(int cid, int qrZoneX, int qrZoneY, int qrZoneWidth, int qrZoneHeight) {
		this.cid = cid;
		this.qrZoneX = qrZoneX;
		this.qrZoneY = qrZoneY;
		this.qrZoneWidth = qrZoneWidth;
		this.qrZoneHeight = qrZoneHeight;
	}

	public ConfigBase(int cid, int qrZoneX, int qrZoneY, int qrZoneWidth, int qrZoneHeight, String uploadLocation, String cmisProtocol, String cmisUri, String cmisUsername, String cmisPassword, String cmisAuthHttpBasic, String cmisRepository, String cmisExportFolder) {
		this.cid = cid;
		this.qrZoneX = qrZoneX;
		this.qrZoneY = qrZoneY;
		this.qrZoneWidth = qrZoneWidth;
		this.qrZoneHeight = qrZoneHeight;
		this.uploadLocation = uploadLocation;
		this.cmisProtocol = cmisProtocol;
		this.cmisUri = cmisUri;
		this.cmisUsername = cmisUsername;
		this.cmisPassword = cmisPassword;
		this.cmisAuthHttpBasic = cmisAuthHttpBasic;
		this.cmisRepository = cmisRepository;
		this.cmisExportFolder = cmisExportFolder;
	}

	@Id

	@Column(name = "CID", unique = true, nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "QR_ZONE_X", nullable = false, length = 10)
	public int getQrZoneX() {
		return this.qrZoneX;
	}

	public void setQrZoneX(int qrZoneX) {
		this.qrZoneX = qrZoneX;
	}

	@Column(name = "QR_ZONE_Y", nullable = false, length = 50)
	public int getQrZoneY() {
		return this.qrZoneY;
	}

	public void setQrZoneY(int qrZoneY) {
		this.qrZoneY = qrZoneY;
	}

	@Column(name = "QR_ZONE_WIDTH", nullable = false, length = 20)
	public int getQrZoneWidth() {
		return this.qrZoneWidth;
	}

	public void setQrZoneWidth(int qrZoneWidth) {
		this.qrZoneWidth = qrZoneWidth;
	}

	@Column(name = "QR_ZONE_HEIGHT", length = 25)
	public int getQrZoneHeight() {
		return this.qrZoneHeight;
	}

	public void setQrZoneHeight(int qrZoneHeight) {
		this.qrZoneHeight = qrZoneHeight;
	}
	
	@Column(name = "UPLOAD_LOCATION", nullable = false, length = 50)
	public String getUploadLocation() {
		return this.uploadLocation;
	}

	public void setUploadLocation(String uploadLocation) {
		this.uploadLocation = uploadLocation;
	}
	
	@Column(name = "CMIS_PROTOCOL", nullable = false, length = 50)
	public String getCmisProtocol() {
		return this.cmisProtocol;
	}

	public void setCmisProtocol(String cmisProtocol) {
		this.cmisProtocol = cmisProtocol;
	}
	
	@Column(name = "CMIS_URI", nullable = false, length = 50)
	public String getCmisUri() {
		return this.cmisUri;
	}

	public void setCmisUri(String cmisUri) {
		this.cmisUri = cmisUri;
	}
	
	@Column(name = "CMIS_USERNAME", nullable = false, length = 50)
	public String getCmisUsername() {
		return this.cmisUsername;
	}

	public void setCmisUsername(String cmisUsername) {
		this.cmisUsername = cmisUsername;
	}
	
	@Column(name = "CMIS_PASSWORD", nullable = false, length = 50)
	public String getCmisPassword() {
		return this.cmisPassword;
	}

	public void setCmisPassword(String cmisPassword) {
		this.cmisPassword = cmisPassword;
	}
	
	@Column(name = "CMIS_AUTH_HTTP_BASIC", nullable = false, length = 50)
	public String getCmisAuthHttpBasic() {
		return this.cmisAuthHttpBasic;
	}

	public void setCmisAuthHttpBasic(String cmisAuthHttpBasic) {
		this.cmisAuthHttpBasic = cmisAuthHttpBasic;
	}
	
	@Column(name = "CMIS_REPOSITORY_ID", nullable = false, length = 50)
	public String getCmisRepository() {
		return this.cmisRepository;
	}

	public void setCmisRepository(String cmisRepository) {
		this.cmisRepository = cmisRepository;
	}
	
	@Column(name = "CMIS_EXPORT_FOLDER", nullable = false, length = 50)
	public String getCmisExportFolder() {
		return this.cmisExportFolder;
	}

	public void setCmisExportFolder(String cmisExportFolder) {
		this.cmisExportFolder = cmisExportFolder;
	}
	
}
