package com.datacap.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PagePropertyZoneBase generated by hbm2java
 */
@Entity
@Table(name = "PAGE_PROPERTY_ZONE_BASE", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = {"PPZID"}) )
public class PagePropertyZoneBase implements java.io.Serializable {

	private int ppzid;
	private int pid;
	private String propertyDisplayName;
	private String propertyId;
	private int zoneX;
	private int zoneY;
	private int zoneWidth;
	private int zoneHeight;
	private String isActive;

	public PagePropertyZoneBase() {
	}

	public PagePropertyZoneBase(int ppzid, int zoneX, int zoneY, int zoneWidth, int zoneHeight) {
		this.ppzid = ppzid;
		this.zoneX = zoneX;
		this.zoneY = zoneY;
		this.zoneWidth = zoneWidth;
		this.zoneHeight = zoneHeight;
	}

	public PagePropertyZoneBase(int ppzid, int pid, String propertyDisplayName, String propertyId, int zoneX, int zoneY, int zoneWidth, int zoneHeight) {
		this.ppzid = ppzid;
		this.pid = pid;
		this.propertyDisplayName = propertyDisplayName;
		this.propertyId = propertyId;
		this.zoneX = zoneX;
		this.zoneY = zoneY;
		this.zoneWidth = zoneWidth;
		this.zoneHeight = zoneHeight;
	}

	@Id

	@Column(name = "PPZID", unique = true, nullable = false)
	public int getPpzid() {
		return this.ppzid;
	}

	public void setPpzid(int ppzid) {
		this.ppzid = ppzid;
	}
	
	@JoinColumn(name = "PID", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "PROPERTY_DISPLAY_NAME", nullable = false, length = 10)
	public String getPropertyDisplayName() {
		return this.propertyDisplayName;
	}

	public void setPropertyDisplayName(String propertyDisplayName) {
		this.propertyDisplayName = propertyDisplayName;
	}

	@Column(name = "PROPERTY_ID", nullable = false, length = 50)
	public String getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(String propertyId) {
		this.propertyId = propertyId;
	}

	@Column(name = "ZONE_X", nullable = false, length = 20)
	public int getZoneX() {
		return this.zoneX;
	}

	public void setZoneX(int zoneX) {
		this.zoneX = zoneX;
	}

	@Column(name = "ZONE_Y", length = 25)
	public int getZoneY() {
		return this.zoneY;
	}

	public void setZoneY(int zoneY) {
		this.zoneY = zoneY;
	}
	
	@Column(name = "ZONE_WIDTH", nullable = false, length = 50)
	public int getZoneWidth() {
		return this.zoneWidth;
	}

	public void setZoneWidth(int zoneWidth) {
		this.zoneWidth = zoneWidth;
	}
	
	@Column(name = "ZONE_HEIGHT", nullable = false, length = 50)
	public int getZoneHeight() {
		return this.zoneHeight;
	}

	public void setZoneHeight(int zoneHeight) {
		this.zoneHeight = zoneHeight;
	}
	
	@Column(name = "IS_ACTIVE", nullable = false, length = 20)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

}
