package com.datacap.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PageBase generated by hbm2java
 */
@Entity
@Table(name = "PAGE_BASE", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = {"PID"}) )
public class PageBase implements java.io.Serializable {

	private int pid;
	private String pageId;
	private String documentClass;
	private String isActive;

	public PageBase() {
	}

	public PageBase(int pid, String pageId, String documentClass, String isActive) {
		this.pid = pid;
		this.pageId = pageId;
		this.documentClass = documentClass;
		this.isActive = isActive;
	}

	@Id

	@Column(name = "PID", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "PAGE_ID", nullable = false, length = 10)
	public String getPageId() {
		return this.pageId;
	}

	public void setPageId(String pageId) {
		this.pageId = pageId;
	}

	@Column(name = "DOCUMENT_CLASS", nullable = false, length = 50)
	public String getDocumentClass() {
		return this.documentClass;
	}

	public void setDocumentClass(String documentClass) {
		this.documentClass = documentClass;
	}

	@Column(name = "IS_ACTIVE", nullable = false, length = 20)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

}
